services:
  horsecountry.api:
    image: ${DOCKER_REGISTRY-}horsecountryapi
    build:
      context: .
      dockerfile: HorseCountry.API/Dockerfile
    depends_on:
      database:
        condition: service_healthy
    ports:
      - 5233:5233
  database:
    image: postgres:latest
    container_name: database
    environment:
      - POSTGRES_DB=HorseCountry
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 7500:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  horshecountry.webapp:
    image: ${DOCKER_REGISTRY-}horsecountrywebapp
    build:
      context: HorseCountry.WebApp
      dockerfile: Dockerfile
    ports:
      - 5173:5173